// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etfksovyggytmpfgdiua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0Zmtzb3Z5Z2d5dG1wZmdkaXVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTAzNTIsImV4cCI6MjA2NTQ2NjM1Mn0.bJPURyf2-QoQfGUxNfbMKdZrm928uzSA7gmdKrtMDGk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);